[colors]
transparent_background_colors = true

[colors.normal]
black = "0x282c34"
blue = "0x51afef"
cyan = "0x46d9ff"
green = "0x98be65"
magenta = "0xc678dd"
red = "0xff6c6b"
white = "0xbbc2cf"
yellow = "0xecbe7b"

[colors.primary]
background = "0x282c34"
foreground = "0xbbc2cf"

[env]
TERM = "alacritty"

[font.normal]
family = "mononoki Nerd Font Mono"
style = "Bold"

[selection]
save_to_clipboard = true

[window]
decorations = "none"
opacity = 0.7
startup_mode = "Maximized"

[[keyboard.bindings]]
key = "A"
mods = "Control"
command = { program = "alacritty", args = ["msg", "config", "window.opacity=1.0"] }

[[keyboard.bindings]]
key = "A"
mods = "Control | Shift"
command = { program = "alacritty", args = ["msg", "config", "window.opacity=0.7"] }
