# If not running interactively, don't do anything

case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
color_prompt=yes

unset color_prompt force_color_prompt

# VI Mode
set -o vi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

# Zoxide support
eval "$(zoxide init bash)"

SSH_ENV="$HOME/.ssh/agent-environment"
# Start SSH agent automatically on login
function start_agent {
    echo "Initialising new SSH agent..."
    /usr/bin/env ssh-agent | sed 's/^echo/#echo/' > "${SSH_ENV}"
    echo succeeded
    chmod 600 "${SSH_ENV}"
    . "${SSH_ENV}" > /dev/null
    /usr/bin/env ssh-add;
}

# Source SSH settings, if applicable

if [ -f "${SSH_ENV}" ]; then
    . "${SSH_ENV}" > /dev/null

ps -ef | grep ${SSH_AGENT_PID} | grep ssh-agent$ > /dev/null || {
    start_agent;
}
else
    start_agent;
fi
. "$HOME/.cargo/env"

# PATH
PATH="$PATH:$HOME/.local/bin"

set_color() {
    local fg=$1
    local bg=$2

    if [ ! -z "$bg" ]; then
        echo "\[\033[38;5;${fg}m\]"
    else
        echo "\[\033[38;5;${fg}m\033[48;5;${bg}m\]"
    fi
}

export -f set_color

host_color=10

case $(hostname -s) in
    EPC-5CG3214891*)
        host_color=193
        ;;
    K80*)
        host_color=161
        ;;
    K8*)
        host_color=203
        ;;
esac

host_color=$(set_color $host_color)
user_color=$(set_color 10)
grey=$(set_color 246)
guix_color=$(set_color 214)
yellow=$(set_color 222)
blue=$(set_color 75)
white=$(set_color 254)

color_path() {
    local path="${PWD/$HOME/~}"
    local current_dir="${path##*/}"
    local parent_dir="${path%/*}"

    echo "${parent_dir}/${blue}${current_dir}"
}

export -f color_path

PS1="${user_color}\u${white}@${host_color}\h\[\033[00m\]:${blue}\w${guix_color}${GUIX_ENVIRONMENT:+ []}\[\033[00m\]\$ "
trap 'echo -ne "\033]0;${PWD}: (${BASH_COMMAND})\007"' DEBUG

# Csharp
dotnet-run() {
    dotnet watch run --project $(basename $PWD)
}

dotnet-test() {
    dotnet test --filter=FullyQualifiedName~$1
}

# Sets up tmux with one editor window and one server process window
tmux-vue() {
    local session_name=$(basename $PWD)
    session_name=$(echo $session_name | sed 's/\./_/')

    if ! tmux has-session -t $session_name 2> /dev/null; then
        tmux new-session -ds $session_name -c $PWD -n $session_name 'guix shell node'
        tmux new-window -t $session_name:2 -n 'server' 'guix shell node -- npm run dev'
    fi

    tmux attach-session -t $session_name
}

# Sets up tmux with one editor window, one server process window and one testing window
tmux-csharp() {
    local session_name=$(basename $PWD)
    session_name=$(echo $session_name | sed 's/\./_/')

    if ! tmux has-session -t "$session_name" 2> /dev/null; then
        tmux new-session -ds "$session_name" -c "$PWD" -n "$session_name"
        tmux new-window -t "$session_name:2" -n 'server'
        tmux new-window -t "$session_name:3" -n 'testing'
    fi

    tmux attach-session -t "$session_name"
}

guix-run() {
    guix shell $1 -- $@
}

