#!/bin/sh

# Sets up tmux with one editor window, one server process window and one testing window

session_name=$(basename $PWD)
session_name=$(echo $session_name | sed 's/\./_/')

if ! tmux has-session -t "$session_name" 2> /dev/null; then
    tmux new-session -ds "$session_name" -c "$PWD" -n "$session_name"
    tmux new-window -t "$session_name:2" -n 'server'
    tmux new-window -t "$session_name:3" -n 'testing'
fi

tmux attach-session -t "$session_name"
